import os
import time
def load ():
    os.system ('clear')
    print ("check your device |■••••••••••••••••••••••••••••••••|")
    time.sleep (0.3)
    os.system ('clear')
    print ("check your device |■■•••••••••••••••••••••••••••••••|")
    time.sleep (0.3)
    os.system ('clear')
    print ("check your device |■■■••••••••••••••••••••••••••••••|")
    time.sleep (0.3)
    os.system ('clear')
    print ("check your device |■■■■•••••••••••••••••••••••••••••|")
    time.sleep (0.3)
    os.system ('clear')
    print ("check your device |■■■■■••••••••••••••••••••••••••••|")
    time.sleep (0.3)
    os.system ('clear')
    print ("check your device |■■■■■■•••••••••••••••••••••••••••|")
    time.sleep (0.3)
    os.system ('clear')
    print ("check your device |■■■■■■■••••••••••••••••••••••••••|")
    time.sleep (0.3)
    os.system ('clear')
    print ("check your device |■■■■■■■■•••••••••••••••••••••••••|")
    time.sleep (0.3)
    os.system ('clear')
    print ("check your device |■■■■■■■■■••••••••••••••••••••••••|")
    time.sleep (0.3)
    os.system ('clear')
    print ("check your device |■■■■■■■■■■•••••••••••••••••••••••|")
    time.sleep (0.3)
    os.system ('clear')
    print ("check your device |■■■■■■■■■■■••••••••••••••••••••••|")
    time.sleep (0.3)
    os.system ('clear')
    print ("check your device |■■■■■■■■■■■■•••••••••••••••••••••|")
    time.sleep (0.3)
    os.system ('clear')
    print ("check your device |■■■■■■■■■■■■■••••••••••••••••••••|")
    time.sleep (0.3)
    os.system ('clear')
    print ("check your device |■■■■■■■■■■■■■■•••••••••••••••••••|")
    time.sleep (0.3)
    os.system ('clear')
    print ("check your device |■■■■■■■■■■■■■■■••••••••••••••••••|")
    time.sleep (0.3)
    os.system ('clear')
    print ("check your device |■■■■■■■■■■■■■■■■•••••••••••••••••|")
    time.sleep (0.3)
    os.system ('clear')
    print ("check your device |■■■■■■■■■■■■■■■■■••••••••••••••••|")
    time.sleep (0.3)
    os.system ('clear')
    print ("check your device |■■■■■■■■■■■■■■■■■■•••••••••••••••|")
    time.sleep (0.3)
    os.system ('clear')
    print ("check your device |■■■■■■■■■■■■■■■■■■■••••••••••••••|")
    time.sleep (0.3)
    os.system ('clear')
    print ("check your device |■■■■■■■■■■■■■■■■■■■■•••••••••••••|")
    time.sleep (0.3)
    os.system ('clear')
    print ("check your device |■■■■■■■■■■■■■■■■■■■■■••••••••••••|")
    time.sleep (0.3)
    os.system ('clear')
    print ("check your device |■■■■■■■■■■■■■■■■■■■■■■•••••••••••|")
    time.sleep (0.3)
    os.system ('clear')
    print ("check your device |■■■■■■■■■■■■■■■■■■■■■■■••••••••••|")
    time.sleep (0.3)
    os.system ('clear')
    print ("check your device |■■■■■■■■■■■■■■■■■■■■■■■■•••••••••|")
    time.sleep (0.3)
    os.system ('clear')
    print ("check your device |■■■■■■■■■■■■■■■■■■■■■■■■■••••••••|")
    time.sleep (0.3)
    os.system ('clear')
    print ("check your device |■■■■■■■■■■■■■■■■■■■■■■■■■■•••••••|")
    time.sleep (0.3)
    os.system ('clear')
    print ("check your device |■■■■■■■■■■■■■■■■■■■■■■■■■■■••••••|")
    time.sleep (0.3)
    os.system ('clear')
    print ("check your device |■■■■■■■■■■■■■■■■■■■■■■■■■■■■•••••|")
    time.sleep (0.3)
    os.system ('clear')
    print ("check your device |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■••••|")
    time.sleep (0.3)
    os.system ('clear')
    print ("check your device |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■•••|")
    time.sleep (0.3)
    os.system ('clear')
    print ("check your device |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■••|")
    time.sleep (0.3)
    os.system ('clear')
    print ("check your device |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■•|")
    time.sleep (0.3)
    os.system ('clear')
    print ("check your device |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■|")
load ()
