import time
import os
os.system ('clear')
print (r"""
|==============================================|
|    install packges to enter the tool ^_^     |
|==============================================|
""")
os.system ('pkg update')
os.system ('pkg upgrade')
os.system ('pkg install wget & openssh & perl -y')
time.sleep (1)
import a
def ban ():
    os.system('clear')
    print ("\033[1;92m                          ************")
    print ("\033[1;92m                         *****************")
    print ("\033[1;92m                       ********************")
    print ("\033[1;92m                        ********************")
    print ("\033[1;92m                         ********")
    print ("\033[1;92m                          ********                 *********")
    print ("\033[1;92m                           ***********              *********")
    print ("\033[1;92m              *********      ****       *            *********")
    print ("\033[1;92m            *            ***               *          *********")
    print ("\033[1;92m          *                       **         *          ********")
    print ("\033[1;92m         *                         **         *       ***********")
    print ("\033[1;92m        *        *****              **      *********************")
    print ("\033[1;92m       *        *******                     *********************")
    print ("\033[1;92m       *         *****                         *****************")
    print ("\033[1;92m       *                                        *")
    print ("\033[1;92m        *     *               *                 *")
    print ("\033[1;92m         *     *             *                  *")
    print ("\033[1;92m           *    *           *                  *")
    print ("\033[1;92m             *    *       *                   *")
    print ("\033[1;92m                *   *****                   *")
    print ("\033[0;93m       ***               *     ************")
    print ("\033[0;93m      *   *            *      *")
    print ("\033[0;93m      *   *          ********* ")     
    print ("\033[0;93m  ****    **********        *          *   *")
    print ("\033[0;93m *               *         *           *   *")
    print ("\033[0;93m*              *           *************    ****")
    print ("\033[0;93m*      *******                                  *")
    print ("\033[0;93m*      *    *                                    *")                                                                                                           
    print ("\033[0;93m  *****    *              *****************      *")
    print ("\033[0;94m          *               *               *      *")                                                                                                           
    print ("\033[0;94m         *      ****      *                 *****")
    print ("\033[0;94m         *    *      **   *")
    print ("\033[0;94m         *   *         ** *")
    print ("\033[0;94m      *** *  *            *")
    print ("\033[0;94m     *    *   *            *    *")
    print ("\033[0;94m      *    *   *           *   * *")                                                                                                                           
    print ("\033[0;94m       *     *  *          *  *  *")
    print ("\033[0;94m         *     * *         *  *  *")                                                                                                                           
    print ("\033[0;94m          *       *        *  *  *")
    print ("\033[0;94m            *       *    *****   *")
    print ("\033[0;94m               *      * * *****  *     STONE TOOL v 3.0 ")
    print ("")
    print ("")
    print ("\033[0;96m》\033[0;92mTO RUN THE TOOL \033[0;91mUSE \033[0;92mTHE PASSWORD\033[0;96m《")
    print ("|")
    print ("|")
    print ("|")
    STN = input ("\033[0;35m|---USE THE TOOL PASSWORD--|>\033[1;32m")
    if STN == "STONE" :
        time.sleep (1)
        import o
        os.system ('clear')
    else :
        print ("\033[0;91mfalse password")
        time.sleep (1)
        ban ()
ban ()
